### PR TITLE
0005: ADD RFD for tink-cli binary for Tinkerbell

### PR DESCRIPTION
**Pull request by Cbkhare**
## Description

Proposal for tink-cli binary for tinkerbell

### CODE REVIEW

**Comment by displague** [comment]
For anyone looking to use the tink-cli outside of Docker, today, I assembled the following notes:
https://github.com/displague/terraform-packet-tinkerbell#run-tink-outside-of-docker

**Comment by displague** [comment]
Related to https://github.com/tinkerbell/tink/issues/73

**Comment by gianarb** [comment]
I do not think we need a proposal for this.
The tink repository has a bunch of issues related to tink-cli and release that we should address in #5 .

My suggestion is to change the status of this proposal to `abandoned`, merge the PR and work on #5

**Comment by Cbkhare** [comment]
Let's take forward the implementation of tink-cli with #5.

**Comment by gianarb** [comment]
Thanks a lot!! Let me know what you think about #5! I am merging this

**Pull request merged**
