### PR TITLE
0019 Propose New Numbering Scheme

### PR DESCRIPTION
**Pull request by mmlb**
## Description

Move away from the numbering scheme currently used (based on Oxide Computer Co, not public) in favor of letting GitHub choose it for us.

-----
[View rendered proposals/0019/README.md](https://github.com/mmlb/proposals/blob/0019/proposals/0019/README.md)

### CODE REVIEW

**Comment by gianarb** [comment]
o.O how did I merge this?

**Comment by mmlb** [comment]
Maybe you were confused with #27?

**Comment by mmlb** [comment]
We can revert and open up a new PR. Hmm also I set branch protections for this repo... :thinking: so *how did* you merge this?

**Comment by gianarb** [comment]
I clicked the button because I didn't see Mergify label!

**Pull request merged**
